

TOKENS = {
        "id": "TK_ID",
        "$": "TK_EOF",

        #Types
        "int": "TK_INT",
        "void": "TK_VOID",
        "char": "TK_CHAR",
        "float": "TK_FLOAT",
        "double": "TK_DOUBLE",
        "long": "TK_LONG",
        "short": "TK_SHORT",
        "string": "TK_STRING",
        "const_int": "TK_CONST_INT",
        "const_real": "TK_CONST_REAL",

        #Reserverd Words
        "asm": "TK_ASM",
        "auto": "TK_AUTO",
        "while": "TK_WHILE",
        "else": "TK_ELSE",
        "if": "TK_IF",
        "break": "TK_BREAK",
        "for": "TK_FOR",
        "return": "TK_RETURN",
        "continue": "TK_CONTINUE",
        "do": "TK_DO",
        "switch": "TK_SWITCH",
        "case": "TK_CASE",
        "default": "TK_DEFAULT",

        #Ops
        "(": "TK_LEFTPAR",
        ")": "TK_RIGHTPAR",
        ",": "TK_COMM",
        ".": "TK_DOT",
        "'": "TK_BACKQUOTE",
        "{": "TK_LEFTBRAC",
        "}": "TK_RIGHTBRAC",
        "!=": "TK_NOTEQUAL",
        "[": "TK_LEFTSQB",
        "]": "TK_RIGHTSQB",
        ":": "TK_COLON",
        ";": "TK_SEMICOLON",
        "!": "TK_NOT",
        "+": "TK_PLUS",
        "++": "TK_PLUSPLUS",
        "+=": "TK_PLUSEQUAL",
        "-": "TK_MINUS",
        "--": "TK_MINUSMINUS",
        "-=": "TK_MINEQUAL",
        "*": "TK_STAR",
        "*=": "TK_STAREQUAL",
        "/": "TK_SLASH",
        "/=": "TK_SLASHEQUAL",
        "|": "TK_LOGICOR",
        "||": "TK_OR",
        "|=": "TK_VERTBAREQUAL",
        "&": "TK_LOGICAND",
        "&&": "TK_AND",
        "&=": "TK_AMPEREQUAL",
        "<": "TK_LESS",
        "<=": "TK_LESSEQUAL",
        "<<": "TK_SHIFTLEFT",
        ">": "TK_GREATER",
        ">=": "TK_GREATEREQUAL",
        ">>": "TK_SHIFTRIGHT",
        "=": "TK_EQUAL",
        "==": "TK_EQUALEQUAL",
        "%": "TK_PERCENT",
        "%=": "TK_PERCENTEQUAL",
        "^": "TK_CIRCUMFLEX"
}